[project]
name = "llm-engineering"
version = "0.1.0"
description = "Exploring LLM and AI engineering concepts."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.1.0",
    "ollama>=0.6.1",
    "openai>=2.16.0",
]
